</td>
 <td width="170">
  <center> 
  <?php include("googleads.inc"); ?>
  </center>
 </td>
  </tr>
</table>


<?php
include("download-both.php");
?>

<p align="center"><br>
<img height="2" src="line.gif" width="730" border="0"><br>
<strong><font color="#000000" face="Comic Sans MS">TheDemoSite.co.uk</font></strong> is a
MySQL database and PHP FREE code example site hosted with: <br>
<b>Seiretto </b><strong><a href="http://www.seiretto.com/">website hosting</a></strong>
Copyright © 1996-2008 Seiretto.&nbsp; All rights reserved.
<br><img height="2" src="line.gif" width="730" border="0"></p>
</body>
</html>
