 <?php
if (!isset($page_title)) $page_title="PHP code and online MySQL database - example username password";
if (!isset($page_keywords)) $page_keywords="free PHP code, mysql sql";
if (!isset($page_desc)) $page_desc="FREE example PHP code and a MySQL database";
?>
<html>

<head>
<title><?php echo $page_title; ?></title>
<meta NAME="keywords" CONTENT="<?php echo $page_keywords; ?>">
<meta NAME="description" CONTENT="<?php echo $page_desc; ?>">
<meta NAME="Content-Language" CONTENT="english">
<meta name="Revisit-after" content="56 days">
<meta name="Distribution" content="Global">
<meta name="Copyright" content="Copyright © 1996-2008 Seiretto.com">
<meta NAME="ROBOTS" CONTENT="ALL">
<link rel="stylesheet" type="text/css" href="tds.css">
</head>

<body BACKGROUND="DiscoverBack.gif"
style="
    SCROLLBAR-ARROW-COLOR: #BBCCFF; 
    SCROLLBAR-TRACK-COLOR: #C9DAF7; 
    SCROLLBAR-FACE-COLOR:  #002163;"
TOPMARGIN="0" LEFTMARGIN="15" MARGINWIDTH="0" MARGINHEIGHT="0">
<div align="center"><center>

<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tr>
    <td width="100%"><p align="center"><img height="2" src="line.gif" width="99%" border="0"
    alt="PHP code examples with database connectivity"></td>
  </tr>
  <tr>
    <td width="100%"><img height="2" src="line.gif" width="99%" border="0"
    alt="PHP code examples with database connectivity"><div align="center"><center><table
    border="0" width="98%" cellspacing="0" cellpadding="0">
      <tr>
        <td width="9%"><font face="Comic Sans MS"><strong><big>&nbsp;PHP.TheDemoSite.co.uk</big></strong></font></td>
        <td><p align="center"><small>Just examples of <b>PHP</b> code, linking to your <b>MySQL</b>
        database and JavaScript.<br>
        <a href="index.php">1. Home</a> | <a href="thedatabase.php">2. The Database</a> | <a
        href="addauser.php">3. Add a User</a> | <a href="login.php">4. Login</a> | <a
        href="getyourowndbonline.php">5. Get your db online</a></small></td>
      </tr>
    </table>
    </center></div></td>
  </tr>
  <tr>
    <td width="100%"><p align="center"><img height="2" src="line.gif" width="99%" border="0"
    alt="PHP code examples with database connectivity"><br>
    </td>
  </tr>
</table>
</center></div>
<p align="center"><i>Also, while here don't forget to have a look at <a href="http://thedemosite.co.uk/phpformmailer/"><strong>phpFormMailer </strong>(easy to use PHP form mail - more secure than many cgi form mail</a>) </i></p>
<? include("hostscripts-12870.inc");?>
</table>

<table border="0" width="100%">
  <tr>
    <td>


